# Generated by Django 2.0.5 on 2018-07-09 07:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20180607_1827'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
                ('answers', django.db.models.manager.Manager()),
            ],
        ),
    ]
