# Generated by Django 2.0.5 on 2018-07-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_session_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='login',
            new_name='username',
        ),
    ]
