# Generated by Django 2.0.5 on 2018-08-10 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_auto_20180809_2100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('objects1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='author1',
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
